"""One-click installer + launcher for UTA + heatmap-sdk.

Idempotent: safe to re-run. Each step (venv, extract, patch, install,
.env, run) checks whether it has already been done and skips if so.

Usage::

    python launcher/_launcher.py            # install (if needed) + run
    python launcher/_launcher.py --setup    # install only, do not run
    python launcher/_launcher.py --reset    # wipe ./.venv + ./heatmap-sdk
                                            # (keeps .env)
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import time
import venv
import webbrowser
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VENV_DIR = REPO_ROOT / ".venv"
HEATMAP_DIR = REPO_ROOT / "heatmap-sdk"
HEATMAP_ZIP = REPO_ROOT / "heatmap-sdk.zip"
PATCH_FILE = (
    REPO_ROOT
    / "trade_adapter"
    / "integrations"
    / "heatmap_sdk"
    / "heatmap_sdk.patch"
)
ENV_FILE = REPO_ROOT / ".env"
BRIDGE_MARKER = HEATMAP_DIR / "app" / "uta_bridge.py"

PYTHON_MIN = (3, 11)

DEFAULT_PORT = 8000
DEFAULT_HOST = "127.0.0.1"


# ---------------------------------------------------------------- helpers --


def _abort(msg: str) -> None:
    print(f"\n[launcher] ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _step(msg: str) -> None:
    print(f"\n[launcher] {msg}")


def _ok(msg: str) -> None:
    print(f"[launcher] OK: {msg}")


def _venv_python() -> Path:
    if os.name == "nt":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def _venv_pip() -> list[str]:
    """Return argv prefix that runs pip inside the venv.

    We use ``python -m pip`` rather than the ``pip`` script directly
    so the call works identically on Windows and POSIX and even
    if the ``pip`` shim was not regenerated by ensurepip.
    """

    return [str(_venv_python()), "-m", "pip"]


# ----------------------------------------------------------------- python --


def check_python() -> None:
    if sys.version_info < PYTHON_MIN:
        _abort(
            f"Python {PYTHON_MIN[0]}.{PYTHON_MIN[1]}+ required, "
            f"got {sys.version.split()[0]}."
        )
    _ok(f"Python {sys.version.split()[0]} >= {PYTHON_MIN[0]}.{PYTHON_MIN[1]}")


# ------------------------------------------------------------------- venv --


def ensure_venv() -> None:
    if _venv_python().exists():
        _ok(f"venv already present at {VENV_DIR}")
        return
    _step(f"creating virtualenv at {VENV_DIR}...")
    builder = venv.EnvBuilder(with_pip=True, clear=False, upgrade_deps=False)
    builder.create(str(VENV_DIR))
    subprocess.check_call([*_venv_pip(), "install", "--upgrade", "pip"])
    _ok("venv created")


# -------------------------------------------------------------- heatmap-sdk --


def ensure_heatmap_extracted() -> None:
    if HEATMAP_DIR.exists() and (HEATMAP_DIR / "app" / "main.py").exists():
        _ok(f"heatmap-sdk already extracted at {HEATMAP_DIR}")
        return
    if not HEATMAP_ZIP.exists():
        _abort(
            f"{HEATMAP_ZIP} not found. Re-clone the UTA repository — "
            "heatmap-sdk.zip ships with it at the repo root."
        )
    _step(f"extracting {HEATMAP_ZIP.name} → {HEATMAP_DIR}...")
    with zipfile.ZipFile(HEATMAP_ZIP) as zf:
        # The zip already contains an app/ tree at top level. Extract
        # directly into ./heatmap-sdk.
        HEATMAP_DIR.mkdir(parents=True, exist_ok=True)
        zf.extractall(HEATMAP_DIR)
    if not (HEATMAP_DIR / "app" / "main.py").exists():
        _abort(
            f"unexpected zip layout — {HEATMAP_DIR}/app/main.py not found "
            f"after extraction"
        )
    _ok("heatmap-sdk extracted")


def ensure_patch_applied() -> None:
    if BRIDGE_MARKER.exists():
        _ok("heatmap-sdk patch already applied (app/uta_bridge.py exists)")
        return
    if not PATCH_FILE.exists():
        _abort(f"patch file missing: {PATCH_FILE}")
    _step(f"applying {PATCH_FILE.name} to {HEATMAP_DIR}...")
    # ``patch -p1`` works cross-platform if GNU patch is on PATH; fall
    # back to a pure-python applier so Windows users don't need to
    # install anything beyond Python itself.
    if shutil.which("patch"):
        subprocess.check_call(
            ["patch", "-p1", "--no-backup-if-mismatch", "-i", str(PATCH_FILE)],
            cwd=str(HEATMAP_DIR),
        )
    else:
        _apply_unified_diff(PATCH_FILE, HEATMAP_DIR)
    if not BRIDGE_MARKER.exists():
        _abort(
            "patch ran but app/uta_bridge.py was not created — patch "
            "is corrupt or did not target the expected files"
        )
    _ok("patch applied")


def _apply_unified_diff(patch_path: Path, target_root: Path) -> None:
    """Minimal pure-python unified-diff applier.

    Handles the subset of diff format produced by ``git diff``: a
    list of file sections, each starting with ``diff --git`` /
    ``--- a/...`` / ``+++ b/...`` followed by one or more hunks
    ``@@ -old,len +new,len @@``. Supports add-file (a/dev/null →
    b/path), delete-file (a/path → b/dev/null) and modify cases.
    Sufficient for our hand-rolled patch; not a general patcher.
    """

    text = patch_path.read_text()
    lines = text.splitlines(keepends=True)
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("diff --git "):
            # Find file headers.
            old_path: str | None = None
            new_path: str | None = None
            i += 1
            while i < len(lines) and not lines[i].startswith("@@"):
                if lines[i].startswith("--- "):
                    old_path = lines[i][4:].strip()
                elif lines[i].startswith("+++ "):
                    new_path = lines[i][4:].strip()
                i += 1
            if new_path is None:
                raise RuntimeError("malformed diff: no +++ header")

            # Strip ``a/`` / ``b/`` prefixes git uses by default.
            def _normalise(p: str) -> str | None:
                if p == "/dev/null":
                    return None
                if p.startswith("a/") or p.startswith("b/"):
                    return p[2:]
                return p

            old_norm = _normalise(old_path or "")
            new_norm = _normalise(new_path)
            assert new_norm is not None

            target = target_root / new_norm
            existing: list[str] = (
                target.read_text().splitlines(keepends=True)
                if old_norm is not None and target.exists()
                else []
            )

            result: list[str] = []
            cursor = 0  # 0-based index into ``existing``
            while i < len(lines) and lines[i].startswith("@@"):
                header = lines[i]
                i += 1
                # Parse ``@@ -a,b +c,d @@`` to locate old start.
                try:
                    minus_part = header.split(" ")[1]
                    old_start = int(minus_part.split(",")[0].lstrip("-"))
                except (IndexError, ValueError) as exc:
                    raise RuntimeError(
                        f"malformed hunk header: {header!r}"
                    ) from exc
                # Lines before this hunk: copy verbatim.
                # ``old_start`` is 1-based; ``old_start == 0`` means
                # an empty-old-file hunk (creating a new file).
                anchor = max(old_start - 1, 0)
                if anchor > cursor:
                    result.extend(existing[cursor:anchor])
                    cursor = anchor
                # Apply hunk body.
                while i < len(lines) and not lines[i].startswith(
                    ("@@", "diff --git ")
                ):
                    body = lines[i]
                    if body.startswith("---") or body.startswith("+++"):
                        i += 1
                        continue
                    if body.startswith(" "):
                        # context — must match existing
                        if (
                            cursor >= len(existing)
                            or existing[cursor] != body[1:]
                        ):
                            raise RuntimeError(
                                f"context mismatch at {new_norm}:{cursor + 1}"
                            )
                        result.append(body[1:])
                        cursor += 1
                    elif body.startswith("-"):
                        if (
                            cursor >= len(existing)
                            or existing[cursor] != body[1:]
                        ):
                            raise RuntimeError(
                                f"deletion mismatch at {new_norm}:{cursor + 1}"
                            )
                        cursor += 1
                    elif body.startswith("+"):
                        result.append(body[1:])
                    elif body.startswith("\\"):
                        # "\ No newline at end of file" marker — ignore.
                        pass
                    else:
                        # blank line inside hunk == context line w/o leading
                        # space (rare but valid)
                        if (
                            cursor >= len(existing)
                            or existing[cursor] != body
                        ):
                            raise RuntimeError(
                                f"blank-context mismatch at "
                                f"{new_norm}:{cursor + 1}"
                            )
                        result.append(body)
                        cursor += 1
                    i += 1
            # Tail of file after last hunk.
            if cursor < len(existing):
                result.extend(existing[cursor:])
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text("".join(result))
        else:
            i += 1


# ---------------------------------------------------------------- pip deps --


def _install_uta_editable() -> None:
    _step("pip install -e . (UTA, editable)...")
    subprocess.check_call(
        [*_venv_pip(), "install", "-e", str(REPO_ROOT)]
    )
    _ok("UTA installed (editable)")


def _install_heatmap_requirements() -> None:
    req = HEATMAP_DIR / "requirements.txt"
    if not req.exists():
        _abort(f"heatmap-sdk requirements.txt not found at {req}")
    _step(f"pip install -r {req.relative_to(REPO_ROOT)}...")
    subprocess.check_call([*_venv_pip(), "install", "-r", str(req)])
    _ok("heatmap-sdk dependencies installed")


def _check_already_installed() -> bool:
    """Best-effort check whether deps were already installed.

    Avoids the multi-second ``pip install`` cold-start when the venv
    is already populated. Re-installation is still safe — pip is a
    no-op when packages are up-to-date — so this is purely a UX win.
    """

    py = _venv_python()
    if not py.exists():
        return False
    result = subprocess.run(
        [
            str(py),
            "-c",
            "import importlib.util as u, sys; "
            "sys.exit(0 if all(u.find_spec(m) for m in "
            "('trade_adapter', 'fastapi', 'uvicorn', 'websockets', "
            "'httpx', 'pydantic', 'numpy', 'dotenv')) else 1)",
        ],
        capture_output=True,
    )
    return result.returncode == 0


def ensure_pip_deps() -> None:
    if _check_already_installed():
        _ok("all Python dependencies already present in venv")
        return
    _install_uta_editable()
    _install_heatmap_requirements()


# ---------------------------------------------------------------- env file --


def _read_env_file() -> dict[str, str]:
    if not ENV_FILE.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_env_file(values: dict[str, str]) -> None:
    body = "\n".join(f"{k}={v}" for k, v in values.items()) + "\n"
    ENV_FILE.write_text(body)
    # 0600 on POSIX; ignored on Windows.
    try:
        os.chmod(ENV_FILE, 0o600)
    except OSError:
        pass


def _prompt(label: str, default: str | None = None, secret: bool = False) -> str:
    suffix = f" [{default}]" if default else ""
    if secret:
        try:
            import getpass

            value = getpass.getpass(f"{label}{suffix}: ")
        except (KeyboardInterrupt, EOFError):
            print()
            sys.exit(130)
    else:
        try:
            value = input(f"{label}{suffix}: ")
        except (KeyboardInterrupt, EOFError):
            print()
            sys.exit(130)
    value = value.strip()
    if not value and default is not None:
        return default
    return value


def ensure_env_file(non_interactive: bool = False) -> None:
    existing = _read_env_file()
    needs_prompt = (
        not existing.get("BINANCE_API_KEY")
        or not existing.get("BINANCE_API_SECRET")
    )
    if not needs_prompt:
        _ok(f".env present at {ENV_FILE} with Binance credentials")
        return
    if non_interactive:
        _abort(
            f"{ENV_FILE} missing BINANCE_API_KEY / BINANCE_API_SECRET. "
            "Run without --no-prompt to enter them interactively, or "
            "write them into .env by hand."
        )
    print()
    print("=" * 60)
    print("First-time setup: Binance API credentials needed.")
    print("Default mode is TESTNET (https://testnet.binancefuture.com).")
    print("Get a testnet key at: https://testnet.binancefuture.com/en/")
    print("=" * 60)
    api_key = _prompt("BINANCE_API_KEY", secret=False)
    api_secret = _prompt("BINANCE_API_SECRET", secret=True)
    if not api_key or not api_secret:
        _abort("API key/secret cannot be empty")
    testnet = _prompt(
        "Use Binance TESTNET? (Y/n)",
        default="Y",
    ).lower().startswith("y")
    notional = _prompt("Default trade size in $ (notional)", default="50")
    sl_pct = _prompt("Default Stop-Loss %", default="2")
    tp_pct = _prompt("Default Take-Profit %", default="1.5")
    autotrade = _prompt(
        "Enable autotrade on start? (y/N — N = manual confirm in UI)",
        default="N",
    ).lower().startswith("y")

    values = dict(existing)
    values["BINANCE_API_KEY"] = api_key
    values["BINANCE_API_SECRET"] = api_secret
    values["UTA_ENABLED"] = "1"
    values["UTA_TESTNET"] = "1" if testnet else "0"
    values["UTA_DEFAULT_NOTIONAL_USD"] = notional
    values["UTA_DEFAULT_SL_PCT"] = str(float(sl_pct) / 100.0)
    values["UTA_DEFAULT_TP_PCT"] = str(float(tp_pct) / 100.0)
    values["UTA_AUTOTRADE_ENABLED"] = "1" if autotrade else "0"
    values.setdefault("UTA_SIGNAL_SOURCE", "binance")
    _write_env_file(values)
    _ok(f".env written to {ENV_FILE}")


# -------------------------------------------------------------------- run --


def run_server(host: str, port: int, open_browser: bool = True) -> int:
    """Launch ``uvicorn app.main:app`` inside the venv.

    Loads ``.env`` into the child process so heatmap-sdk + UTA see
    the configured credentials. Blocks until uvicorn exits.
    """

    env = os.environ.copy()
    env.update(_read_env_file())
    # Add heatmap-sdk root and UTA root to PYTHONPATH so ``app.main``
    # resolves without a manual ``cd``.
    sep = ";" if os.name == "nt" else ":"
    env["PYTHONPATH"] = sep.join(
        [str(HEATMAP_DIR), str(REPO_ROOT), env.get("PYTHONPATH", "")]
    ).rstrip(sep)
    _step(f"launching uvicorn at http://{host}:{port}/...")
    print(f"[launcher] press Ctrl-C to stop\n")
    proc = subprocess.Popen(
        [
            str(_venv_python()),
            "-m",
            "uvicorn",
            "app.main:app",
            "--host",
            host,
            "--port",
            str(port),
        ],
        cwd=str(HEATMAP_DIR),
        env=env,
    )
    if open_browser:
        # Give uvicorn ~2 seconds to bind before launching the browser.
        try:
            time.sleep(2.0)
            webbrowser.open(f"http://{host}:{port}/")
        except Exception:
            # Browser auto-open is a convenience, never a hard error.
            pass
    try:
        return proc.wait()
    except KeyboardInterrupt:
        # Forward Ctrl-C to uvicorn so it tears down cleanly.
        proc.terminate()
        try:
            return proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            return proc.wait()


# -------------------------------------------------------------- entrypoint --


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="One-click installer + launcher for UTA + heatmap-sdk"
    )
    parser.add_argument(
        "--setup",
        action="store_true",
        help="install only, do not launch the server",
    )
    parser.add_argument(
        "--no-prompt",
        action="store_true",
        help="abort if .env is missing instead of prompting interactively",
    )
    parser.add_argument(
        "--no-browser",
        action="store_true",
        help="do not auto-open the browser after the server starts",
    )
    parser.add_argument("--host", default=DEFAULT_HOST, help="bind host")
    parser.add_argument(
        "--port", type=int, default=DEFAULT_PORT, help="bind port"
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="wipe ./.venv and ./heatmap-sdk (keeps .env)",
    )
    args = parser.parse_args(argv)

    if args.reset:
        for d in (VENV_DIR, HEATMAP_DIR):
            if d.exists():
                _step(f"removing {d}...")
                shutil.rmtree(d)
        _ok("reset complete. Re-run without --reset to reinstall.")
        return 0

    check_python()
    ensure_venv()
    ensure_heatmap_extracted()
    ensure_patch_applied()
    ensure_pip_deps()
    ensure_env_file(non_interactive=args.no_prompt)

    if args.setup:
        print()
        _ok("setup complete. Run again without --setup to launch the server.")
        return 0

    return run_server(
        host=args.host, port=args.port, open_browser=not args.no_browser
    )


if __name__ == "__main__":
    sys.exit(main())
